### ISSUE TITLE
deploy_test_pruned.py

### ISSUE THREAD

**Issue by huyong1109** [garion9013/impl-pruning-TF#1]
Very nice work! A few tiny issues: 
1. in the readMe, "./deploy_test_pruned.py -d -m model_ckpt_sparse_retrained" 
2. there is a "execfile('/home/yhlinux/.pythonrc')" in deploy_test_pruned.py. Anything important in pythonrc? 
Thanks!

**Comment by younghwanoh** [comment]
HI, huyong! Sorry for a late response.
The code you mentioned is just for debugging and it should be removed.
It's my mistake and I've just fixed it.
Thank you.

**Comment by huyong1109** [comment]
Thanks so much!  There are some new features for sparse tensor in TF 9.0, like 'sparse_tensor_dense_matmul'. I am going to try that.

**Comment by pribadihcr** [comment]
Hi @huyong1109,

The deploy_test_pruned is work ?

**Comment by huyong1109** [comment]
@pribadihcr  Yes, I tried that before. It works, but slower somehow.

**Comment by pribadihcr** [comment]
@huyong1109 can you post the code?

Thanks
