### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by liuhengli** [garion9013/impl-pruning-TF#10]
using the 'model_ckpt_sparse_retrained' file test is true, but instead of this './sparse_model_extreme/model_ckpt_sparse_retrained' model file will error occurred，'InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1014,2] rhs shape= [1657,2]'.

**Comment by younghwanoh** [comment]
Yes, this is not good.
Every time you apply different percentage of pruning, you should set the corresponding shape of tensor to target FC layers.
For your cases, 1014 & 1657 should be changed to the number of non-zero elements from your model.
