### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by LXWDL** [garion9013/impl-pruning-TF#14]
Hi,thanks for your codes. When i run the "python train.py -2 -3", i encounter the error:
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
and i don't konw how to solver it,thanks for your help.

**Comment by Connor323** [comment]
I also find this error; I guess is caused by different version of numpy or python. You can just change `-under_threshold` to `np.logical_not(under_threshold)` to fix it.
