### ISSUE TITLE
assign operations cause OOM for vgg_16

### ISSUE THREAD

**Issue by zuowang** [garion9013/impl-pruning-TF#16]
@garion9013 
Hi-
I modified your code to compress vgg_16 model. The assign operations in 
'''
def apply_prune(weights):
'''
cause OOM. 
My GPU cache is 8GB. It dosen't work even I choose a very small batch size.

Is there any way to make it work for large model like vgg_16?  Pytorch is prefer in this aspect:(

**Comment by PAPL-SKKU** [comment]
Maybe you can workaround with setting Tensorflow to run on CPU for the job. (second round)
or I'm not 100% sure it's possible, but you can make the specific ops, **tf.assign** in apply_prune,
run on CPU.

For the details about changing your device for sessions, why don't you try [this](https://www.tensorflow.org/tutorials/using_gpu)?

**Comment by younghwanoh** [comment]
Maybe you can workaround with setting Tensorflow to run on CPU for the job. (second round)
or I'm not 100% sure it's possible, but you can make the specific ops, **tf.assign** in apply_prune,
run on CPU.

For the details about changing your device for sessions, why don't you try [this](https://www.tensorflow.org/tutorials/using_gpu)?

The source of problem might be duplicated usage of total weights in this codes.
If you have better solutions, please notify me.
