### ISSUE TITLE
Accuracy problem with the code

### ISSUE THREAD

**Issue by gclouding** [garion9013/impl-pruning-TF#2]
Hi, I just downloaded your code, and run "python train.py -2". And the following is the log printed out automatically.
w_fc1 threshold:    0.148615
Non-zero count (w_fc1): 321130
w_fc2 threshold:    0.15566
Non-zero count (w_fc2): 1024
Second-round prune-only test accuracy 0

step 0, training accuracy 0.06
step 100, training accuracy 0.08
step 200, training accuracy 0.06
step 300, training accuracy 0.1
step 400, training accuracy 0.12
step 500, training accuracy 0.1
step 600, training accuracy 0.1
step 700, training accuracy 0.06
step 800, training accuracy 0.08
step 900, training accuracy 0.1
step 1000, training accuracy 0.02
step 1100, training accuracy 0.24
step 1200, training accuracy 0.06
step 1300, training accuracy 0.08
step 1400, training accuracy 0.08
step 1500, training accuracy 0.1
step 1600, training accuracy 0.02
step 1700, training accuracy 0.08
step 1800, training accuracy 0.12
step 1900, training accuracy 0.16
step 2000, training accuracy 0.04
step 2100, training accuracy 0.08
step 2200, training accuracy 0.06
step 2300, training accuracy 0.06
step 2400, training accuracy 0.04
step 2500, training accuracy 0.12
step 2600, training accuracy 0.14
step 2700, training accuracy 0.1
step 2800, training accuracy 0.06
step 2900, training accuracy 0.1
step 3000, training accuracy 0.12
step 3100, training accuracy 0.1
step 3200, training accuracy 0.12
step 3300, training accuracy 0.12
step 3400, training accuracy 0.18
step 3500, training accuracy 0.16
step 3600, training accuracy 0.08
step 3700, training accuracy 0.1
step 3800, training accuracy 0
step 3900, training accuracy 0.16
step 4000, training accuracy 0.12
step 4100, training accuracy 0.08
step 4200, training accuracy 0.14
step 4300, training accuracy 0.16
Second-round final test accuracy 0.0978

We can see that the training accuracy is very low when using pruning and retraining for MNIST.
Is there any ideas ?

**Comment by younghwanoh** [comment]
OK. Your config.py seems 90% off as a default.
But, after pruning it test accuracy falls to 0.
I recommend you to check if _model_ckpt_dense_ file is corrupted.

```
git checkout model_ckpt_dense
```

If the problem persists,
On what platforms did you try it?
CPU or GPU, Tensorflow 0.8 or 0.10 and so on.

Wth Tensorflow 0.10 and CPU,

```
w_fc1 threshold:    0.148615
Non-zero count (w_fc1): 321130
w_fc2 threshold:    0.15566
Non-zero count (w_fc2): 1024
Second-round prune-only test accuracy 0.9532

step 0, training accuracy 0.96
step 100, training accuracy 0.98
step 200, training accuracy 1
step 300, training accuracy 0.98
step 400, training accuracy 1
step 500, training accuracy 0.98
step 600, training accuracy 0.98
step 700, training accuracy 1
step 800, training accuracy 1
...
```

This log messages should be printed out

**Comment by gclouding** [comment]
I am using Tensorflow verion 0.11.
After I commented out the test code "score = test(y_conv, message="First-round test accuracy")" in the train.py, the training accuracy of the second round (pruning and retraining phase) is correct as your results.

After the first and second round of training, I use "python deploy_test.py -t" to test, it printed out:
test accuracy 0
time: 1.61593413353 s

However, we I test a single image using "python deploy_test.py -d", it printed out:
output: [7]
time: 0.331609964371 s

So I guess there maybe some wrong with the test phase using the test dataset.

**Comment by younghwanoh** [comment]
With my platform, I cannot reproduce your problem now.
I'll try this after upgrading tensorflow versions.
Thanks for the reports.

**Comment by younghwanoh** [comment]
As you pointed out, there is strange duplication in test() on _first_round_
I somewhat doubt that this commit will help you, but
could you try the latest commit? -- 3ccc55cf05b295970c0e64c5aee7646550306cf7
Also, with Tensorflow 0.11rc (CPU, pip install) I could not reproduce your case.

**Comment by gclouding** [comment]
@garion9013 
I followed the latest commit, the test accuracy is still 0. The log printed out is : 
step 0, training accuracy 0.12
step 100, training accuracy 0.8
step 200, training accuracy 0.94
step 300, training accuracy 0.84
step 400, training accuracy 1
step 500, training accuracy 0.9
step 600, training accuracy 0.98
step 700, training accuracy 0.96
step 800, training accuracy 0.88
step 900, training accuracy 1
step 1000, training accuracy 0.94
step 1100, training accuracy 0.94
step 1200, training accuracy 1
step 1300, training accuracy 0.98
step 1400, training accuracy 0.96
step 1500, training accuracy 0.98
step 1600, training accuracy 1
step 1700, training accuracy 0.94
step 1800, training accuracy 0.94
step 1900, training accuracy 0.98
First-round test accuracy 0

**Comment by garion9013** [comment]
I recommend to check your mnist.test dataset is correctly provided to this code.
FYI, I've updated batched validation to avoid OOM -- 75d3a08dacbbf44c25acc2f4707154e17470577d

**Comment by younghwanoh** [comment]
I recommend to check your mnist.test dataset is correctly provided to this code.
FYI, I've updated batched validation to avoid OOM -- 75d3a08dacbbf44c25acc2f4707154e17470577d
