### ISSUE TITLE
How the values in the thspace.py were obained?

### ISSUE THREAD

**Issue by kamadforge** [garion9013/impl-pruning-TF#3]
How were all the values calculated? For example, did the thresholds to get given level of pruning were obtained by experimenting which value result in a k% pruning and then this value was hardcoded?

**Comment by younghwanoh** [comment]
Yes, exactly. As you mentioned, I've firstly pruned k% of weights off and hardcoded the threshold values. While retraining and pruning process, I've retained those thresholds. This work was just for quantifying the performance aspects of iterative pruning, but, do you have any better ideas?

**Comment by kamadforge** [comment]
If the thresholds are hard-coded with the initial training values and the retraining changes some of the values past the threshold than the result may not be exactly k% pruned weights. Am I understandaing it right? What about taking all the weights, sorting them and setting bottom k% of values to 0?
