### ISSUE TITLE
Pruning convolutional layers

### ISSUE THREAD

**Issue by kamadforge** [garion9013/impl-pruning-TF#4]
It seems that the current version prunes only the fully connected layers. Is it possible to prune convolutional layers, as well?

**Comment by younghwanoh** [comment]
The paper author insists that it's possible by representing 4D Tensor into low-dimensional Array.
But, I think its array indexing is very tricky and implementing those are quite boring things.
Anyway, it's possible if you have a efficient sparse matrix representation for 4D Tensor. Using TensorFlow?, I'm not 100% sure, but possible.

**Comment by pribadihcr** [comment]
Hi @garion9013,

Is there update about how to prune convolutional layer in tensorflow?
Thanks
