### ISSUE TITLE
Applying pruning on gradients

### ISSUE THREAD

**Issue by kamadforge** [garion9013/impl-pruning-TF#6]
As far as I can tell, before retraining we are manipulating gradients. How does the function "apply_prune_on_grads" do it and what is the result and the effect of applying pruning on gradients on the retraining phase?

**Comment by younghwanoh** [comment]
_apply_prune_on_grads_ "masks" gradient matrix to keep the pruned weights to be zero.
Therefore, no updates to pruned weights.

**Comment by kamadforge** [comment]
Fair enough, that's clear. Btw. congratulations on a very good work. 수고하셨습니다.
