### ISSUE TITLE
“could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM”

### ISSUE THREAD

**Issue by zhyiwei** [garion9013/impl-pruning-TF#7]
Excuse me, I downloaded your code, and changed the path of mnist-dataset , just like:
"mnist = input_data.read_data_sets('/tmp/data/', one_hot=True) "  ==>  "mnist = input_data.read_data_sets('/home/amax/zhyiwei/tensorflow/data_set/mnist/', one_hot=True)"

Then i ran "python train.py -2 -3",but it looked like something wrong (Python 2.7.6 & Tensorflow '0.8.0' ) :

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Extracting /home/amax/zhyiwei/tensorflow/data_set/mnist/train-images-idx3-ubyte.gz
Extracting /home/amax/zhyiwei/tensorflow/data_set/mnist/train-labels-idx1-ubyte.gz
Extracting /home/amax/zhyiwei/tensorflow/data_set/mnist/t10k-images-idx3-ubyte.gz
Extracting /home/amax/zhyiwei/tensorflow/data_set/mnist/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Tesla M40 24GB
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:02:00.0
Total memory: 22.43GiB
Free memory: 22.32GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:02:00.0)
w_fc1 threshold:        0.148615
Non-zero count (w_fc1): 320939
w_fc2 threshold:        0.15566
Non-zero count (w_fc2): 1014
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

**Comment by PAPL-SKKU** [comment]
It seems that cudnn version issues. I think your tensorflow installation might be the problem.
TF 0.8.0 is quite old already, you may have to check 0.8.0 is compatible to your cuDNN version.

**Comment by younghwanoh** [comment]
It seems that cudnn version issues.
TF 0.8.0 is quite old already, you may have to check 0.8.0 is compatible to your cuDNN version.
